; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega328P]
platform = atmelavr
board = ATmega328P

build_type = debug

extra_scripts =
 	post:scripts/copy_sources_for_proteus.py

upload_protocol = arduino


###-----------------------SIM-AVR (descomentar para usar simulador avr)----------------------
; debug_tool = simavr
; debug_server =
; 	${platformio.packages_dir}/tool-simavr/bin/simavr
; 	-g
; 	-v
; 	-m
; 	atmega328p
; 	-f
; 	16000000
; 	$PROG_PATH
; build_flags =
;     -Wl,--undefined=_mytrace
; #Sin estas flags ignora el simbolo _mytrace y no se generan los archivos de trazas, aunque se use la version de simavr con soporte para trazas.
###--------------------------------------------------------------------------------------------------

###----------AVR-STUB: descomentar para usar el AVR-STUB (debugger por hardware)---------------------
debug_tool = avr-stub
debug_port = /dev/ttyACM1 #Especificar el puerto serie al que esta conectado la placa arduino
lib_deps =
    jdolinay/avr-debugger @ ~1.4
debug_build_flags = 
  -O0 
  -ggdb3
  -DAVR8_BREAKPOINT_MODE=1 
  -DAVR8_SWINT_SOURCE=1 ; Usar INT1 (PD3) para el debugger y dejar libre INT0 (PD2)
###--------------------------------------------------------------------------------------------------